export const INITIAL_CUSTOMERS = [
  {
    id: '1',
    businessName: 'Pinnacle Telecom Solutions',
    contactPerson: 'Amaka Iroegbu',
    type: 'Corporation',
    industry: 'Telecommunications',
    rm: { name: 'Ada', initials: 'AN' },
    status: 'Active',
    createdDate: '10 Jun 2024',
  },
  {
    id: '2',
    businessName: 'Sterling Media Works Ltd',
    contactPerson: 'Sola Martins',
    type: 'LLC',
    industry: 'Media',
    rm: { name: 'John', initials: 'JA' },
    status: 'Active',
    createdDate: '28 May 2024',
  },
  {
    id: '3',
    businessName: 'Atlantic Shipping Company Ltd',
    contactPerson: 'Yemi Adebayo',
    type: 'LLC',
    industry: 'Logistics',
    rm: { name: 'James', initials: 'JM' },
    status: 'Active',
    createdDate: '15 May 2024',
  },
  {
    id: '4',
    businessName: 'SunRise Energy Resources',
    contactPerson: 'Femi Coker',
    type: 'Corporation',
    industry: 'Energy',
    rm: { name: 'Kemi', initials: 'KA' },
    status: 'Pending',
    createdDate: '02 May 2024',
  },
  {
    id: '5',
    businessName: 'Apex Management Consulting',
    contactPerson: 'Amara Nwosu',
    type: 'LLC',
    industry: 'Professional Services',
    rm: { name: 'Ada', initials: 'AN' },
    status: 'Active',
    createdDate: '14 Apr 2024',
  },
  {
    id: '6',
    businessName: 'Zenith Construction plc',
    contactPerson: 'Tunde Bello',
    type: 'Corporation',
    industry: 'Construction',
    rm: { name: 'Sarah', initials: 'SO' },
    status: 'Active',
    createdDate: '01 Apr 2024',
  },
  {
    id: '7',
    businessName: 'GlobalMart Retail Group',
    contactPerson: 'Emeka Okafor',
    type: 'Corporation',
    industry: 'Retail',
    rm: { name: 'John', initials: 'JA' },
    status: 'Pending',
    createdDate: '18 Mar 2024',
  },
  {
    id: '8',
    businessName: 'Cornerstone Realty Partners',
    contactPerson: 'Chioma Obi-Williams',
    type: 'Partnership',
    industry: 'Real Estate',
    rm: { name: 'Kemi', initials: 'KA' },
    status: 'Active',
    createdDate: '05 Mar 2024',
  },
  {
    id: '9',
    businessName: 'Nova Healthcare Group',
    contactPerson: 'Dr. Ngozi Eze',
    type: 'Corporation',
    industry: 'Healthcare',
    rm: { name: 'Ada', initials: 'AN' },
    status: 'Active',
    createdDate: '22 Feb 2024',
  },
  {
    id: '10',
    businessName: 'BlueStar Logistics Ltd',
    contactPerson: 'Kwame Mensah',
    type: 'LLC',
    industry: 'Logistics',
    rm: { name: 'James', initials: 'JM' },
    status: 'Pending',
    createdDate: '10 Feb 2024',
  },
  {
    id: '11',
    businessName: 'Horizon Financial Tech',
    contactPerson: 'Babatunde Ojo',
    type: 'Corporation',
    industry: 'Finance',
    rm: { name: 'Sarah', initials: 'SO' },
    status: 'Active',
    createdDate: '28 Jan 2024',
  },
  {
    id: '12',
    businessName: 'Crestview Agribusiness',
    contactPerson: 'Fatima Aliyu',
    type: 'LLC',
    industry: 'Agriculture',
    rm: { name: 'Kemi', initials: 'KA' },
    status: 'Inactive',
    createdDate: '15 Jan 2024',
  },
  {
    id: '13',
    businessName: 'Summit Hospitality Group',
    contactPerson: 'Chidi Ebere',
    type: 'Corporation',
    industry: 'Hospitality',
    rm: { name: 'Ada', initials: 'AN' },
    status: 'Inactive',
    createdDate: '05 Jan 2024',
  },
  {
    id: '14',
    businessName: 'Vanguard Security Systems',
    contactPerson: 'Ibrahim Musa',
    type: 'LLC',
    industry: 'Security',
    rm: { name: 'James', initials: 'JM' },
    status: 'Active',
    createdDate: '20 Dec 2023',
  },
  {
    id: '15',
    businessName: 'Nexa Digital Labs',
    contactPerson: 'Uche Nnamdi',
    type: 'Partnership',
    industry: 'Technology',
    rm: { name: 'John', initials: 'JA' },
    status: 'Inactive',
    createdDate: '10 Dec 2023',
  },
];

export const INDUSTRIES = [
  'All Industries',
  'Telecommunications',
  'Media',
  'Logistics',
  'Energy',
  'Professional Services',
  'Construction',
  'Retail',
  'Real Estate',
  'Healthcare',
  'Finance',
  'Agriculture',
  'Hospitality',
  'Security',
  'Technology',
];
